export type TemplateLanguage = "ko" | "en";
export type TemplateAutoMode = "on" | "off";
export type TemplateTeamsMode = "on" | "off";
export type TemplateProvider = "codex";
import {
  CORE_WORKFLOW_SKILLS,
  MANDATORY_IMPLEMENTATION_CRITERIA_EN,
  MANDATORY_IMPLEMENTATION_CRITERIA_KO,
  OPTIONAL_AUDIT_SKILLS,
  WORKFLOW_FRONTMATTER_SKILLS,
  WORKFLOW_FRONTMATTER_STAGES,
  type WorkflowSkillName
} from "./workflow-contract.js";

export interface TemplateInput {
  language: TemplateLanguage;
  autoMode: TemplateAutoMode;
  teamsMode: TemplateTeamsMode;
  provider: TemplateProvider;
  version: string;
}

export interface GeneratedFileTemplate {
  path: string;
  content: string;
  executable?: boolean;
  preserveExistingContent?: boolean;
}

function lines(parts: string[]): string {
  return `${parts.join("\n")}\n`;
}

function numberedCoreWorkflowSkillLines(): string[] {
  return CORE_WORKFLOW_SKILLS.map((skill, index) => `${index + 1}. \`${skill}\``);
}

function optionalAuditSkillLines(): string[] {
  return OPTIONAL_AUDIT_SKILLS.map((skill) => `- \`${skill}\``);
}

function mandatoryCriteriaSection(language: TemplateLanguage): string[] {
  const title =
    language === "ko" ? "## Mandatory Implementation Criteria" : "## Mandatory Implementation Criteria";
  const criteria =
    language === "ko" ? MANDATORY_IMPLEMENTATION_CRITERIA_KO : MANDATORY_IMPLEMENTATION_CRITERIA_EN;

  return ["", title, "", ...criteria.map((criterion) => `- ${criterion}`)];
}

function verificationContractRule(language: TemplateLanguage): string {
  return language === "ko"
    ? "- 대상 프로젝트 검증 명령은 선언된 current-project verification contract가 있을 때만 자동 실행 후보가 되며, 없으면 `manual verification required`로 남긴다."
    : "- Treat project verification commands as auto-runnable only when a declared current-project verification contract exists; otherwise keep `manual verification required`.";
}

function auditApplicabilityExamples(language: TemplateLanguage): string[] {
  return language === "ko"
    ? [
        "- 형식 예시: `- [pgg-token]: [required|not_required] | <짧은 근거>`",
        "- 형식 예시: `- [pgg-performance]: [required|not_required] | <짧은 근거>`"
      ]
    : [
        "- Example format: `- [pgg-token]: [required|not_required] | <short rationale>`",
        "- Example format: `- [pgg-performance]: [required|not_required] | <short rationale>`"
      ];
}

function auditApplicabilityContractSection(language: TemplateLanguage): string[] {
  if (language === "ko") {
    return [
      "### Audit Applicability Contract",
      "",
      "- `plan.md`, `task.md`, `state/current.md`, `qa/report.md`에는 `Audit Applicability` 섹션을 두고 아래 형식을 맞춘다.",
      ...auditApplicabilityExamples(language)
    ];
  }

  return [
    "### Audit Applicability Contract",
    "",
    "- `plan.md`, `task.md`, `state/current.md`, and `qa/report.md` should share an `Audit Applicability` section.",
    ...auditApplicabilityExamples(language)
  ];
}

function auditApplicabilityStateRule(language: TemplateLanguage): string {
  return language === "ko"
    ? "- `Audit Applicability` 섹션의 상태와 짧은 근거를 최소 컨텍스트에 유지한다."
    : "- Preserve the `Audit Applicability` section with status and rationale in the minimum handoff.";
}

function agentsMd(input: TemplateInput): string {
  if (input.language === "ko") {
    return lines([
      "# AGENTS.md",
      "",
      "## Codex 전용 작업 원칙",
      "",
      "- 모든 작업은 `.codex/add/WOKR-FLOW.md`를 따른다.",
      "- 모든 topic은 `poggn/active/<topic>` 안에서만 진행한다.",
      "- 구현 전에는 반드시 `proposal.md`, `plan.md`, `task.md`를 확인한다.",
      "- 구현 단계에서는 `spec/*/*.md` 기준을 위반하지 않는다.",
      "- 다음 단계로 넘길 때는 전체 문맥이 아니라 `state/current.md`만 우선 전달한다.",
      "- `pgg teams`가 `on`이면 stage 시작 전에 `pgg-state-pack.sh`로 최소 컨텍스트를 만들고 전문가 roster 기반 자동 orchestration을 사용한다.",
      "- core workflow(`pgg-add`, `pgg-plan`, `pgg-code`, `pgg-refactor`, `pgg-qa`)와 필요 시 여는 optional audit(`pgg-token`, `pgg-performance`)의 현재 프로젝트 내부 확인/기록/생성 절차는 추가 허락 없이 자동 처리한다.",
      "- proposal 단계에서 `archive_type`을 `feat`, `fix`, `docs`, `refactor`, `chore`, `remove` 중 하나로 확정한다.",
      "- pgg가 생성·관리하는 `.codex/sh/*.sh` helper만 workflow 내부 trusted script로 보고 추가 허락 없이 실행한다.",
      verificationContractRule(input.language),
      "- 파일 생성/수정/삭제는 `implementation/index.md`와 `implementation/diffs/*.diff`에 기록한다.",
      "- 검증이 통과된 topic은 version 기록 후 `poggn/archive/<topic>`으로 이동한다.",
      "- archive 처리된 topic은 다시 active로 되돌리지 않는다.",
      "",
      "## Core Skill Flow",
      "",
      ...numberedCoreWorkflowSkillLines(),
      "",
      "## Optional Audits",
      "",
      ...optionalAuditSkillLines(),
      "",
      "## 금지",
      "",
      "- `proposal.md`, `plan.md`, `task.md` 없이 구현하지 않는다.",
      "- auto mode가 `off`일 때 불확실한 요구사항을 임의 확정하지 않는다.",
      "- teams handoff에 전체 문서를 기본값으로 넘기지 않는다.",
      "- 전체 파일 내용을 불필요하게 다음 단계에 전달하지 않는다.",
      "- diff로 충분한 경우 전체 파일을 복사하지 않는다."
    ]);
  }

  return lines([
    "# AGENTS.md",
    "",
    "## Codex Working Rules",
    "",
    "- Follow `.codex/add/WOKR-FLOW.md` for every task.",
    "- Work on every topic only inside `poggn/active/<topic>`.",
    "- Read `proposal.md`, `plan.md`, and `task.md` before implementation.",
    "- Do not violate `spec/*/*.md` during implementation.",
    "- Pass only `state/current.md` to the next stage before larger context.",
    "- When `pgg teams` is `on`, build the minimum handoff with `pgg-state-pack.sh` before expert-roster-based automatic orchestration.",
    "- Automatically handle stage-local confirmations, records, and generated documents for the core workflow (`pgg-add`, `pgg-plan`, `pgg-code`, `pgg-refactor`, `pgg-qa`) plus any required optional audit (`pgg-token`, `pgg-performance`) when the work stays inside the current project.",
    "- Resolve `archive_type` as one of `feat`, `fix`, `docs`, `refactor`, `chore`, `remove` during the proposal stage.",
    "- Treat only pgg-generated and managed `.codex/sh/*.sh` helpers as trusted workflow scripts that can run without extra approval.",
    verificationContractRule(input.language),
    "- Record file creation, updates, and deletions in `implementation/index.md` and `implementation/diffs/*.diff`.",
    "- Move verified topics to `poggn/archive/<topic>` only after recording the archive version.",
    "- Do not move archived topics back to `active`.",
    "",
    "## Core Skill Flow",
    "",
    ...numberedCoreWorkflowSkillLines(),
    "",
    "## Optional Audits",
    "",
    ...optionalAuditSkillLines(),
    "",
    "## Forbidden",
    "",
    "- Do not implement without `proposal.md`, `plan.md`, and `task.md`.",
    "- Do not lock uncertain requirements when auto mode is `off`.",
    "- Do not forward full documents as the default teams handoff.",
    "- Do not forward full files to the next stage unless necessary.",
    "- Do not copy full files when a diff is enough."
  ]);
}

function workFlowMd(input: TemplateInput): string {
  if (input.language === "ko") {
    return lines([
      "# Work Flow",
      "",
      "pgg는 core workflow와 필요할 때만 여는 optional audit로 delivery를 분리한다.",
      "",
      "## 절대 원칙",
      "",
      "- auto mode가 `off`이면 미확정 요구사항은 선택지와 직접 입력으로 남긴다.",
      "- `pgg teams`가 `on`이면 stage별 전문가 자동 orchestration을 사용하고, `off`이면 단일 에이전트 흐름을 사용한다.",
      "- 현재 프로젝트 내부 문서 생성, 확인, 기록 절차는 stage 안에서 자동 처리하고, 외부 경로나 전역 상태를 건드리는 작업은 자동 처리하지 않는다.",
      "- pgg가 생성·관리하는 `.codex/sh/*.sh` helper만 workflow 내부 trusted script로 보고 추가 허락 없이 실행한다.",
      "- TTY 선택형 인터랙션은 방향키와 Enter 기반 공통 메뉴를 사용한다.",
      "- interactive 변경 명령은 변경 경로 또는 no-op/cancel 상태를 출력한 뒤 종료한다.",
      "- 구현 전에는 `proposal.md`, `plan.md`, `task.md`를 기준으로 범위와 완료 조건을 확인한다.",
      "- 모든 작업은 `poggn/active/<topic>` 문서를 따라 진행한다.",
      "- proposal 단계에서 `archive_type`과 `project_scope`를 확정해 다음 stage와 archive helper가 같은 값을 사용하게 한다.",
      "- 대상 프로젝트 검증은 선언된 current-project verification command contract만 사용하고, framework 명령을 추론 실행하지 않는다.",
      "- QA를 통과한 topic만 archive로 이동한다.",
      "- 각 단계는 필요한 전문가 평가를 포함한다.",
      "",
      "## 전체 실행 흐름",
      "",
      "### Core Workflow",
      "",
      "1. `pgg-add`",
      "   - topic 생성",
      "   - `proposal.md`, `reviews/proposal.review.md`, `state/current.md`, `workflow.reactflow.json` 생성",
      "   - 사용자 입력 질문 기록과 current-project 범위 내부 확인/기록 절차, `archive_type` 확정",
      "2. `pgg-plan`",
      "   - `plan.md`, `task.md`, `spec/*/*.md`, `reviews/plan.review.md`, `reviews/task.review.md` 생성",
      "3. `pgg-code`",
      "   - 코드 구현",
      "   - `implementation/index.md`, `implementation/diffs/*.diff`, `reviews/code.review.md` 생성",
      "4. `pgg-refactor`",
      "   - 레거시 코드 제거와 구조 개선 수행",
      "   - `reviews/refactor.review.md` 생성",
      "5. `pgg-qa`",
      "   - `qa/report.md` 생성",
      "   - `qa/report.md`가 pass면 `.codex/sh/pgg-archive.sh <topic|topic_dir>` 실행",
      "   - archive helper가 `version.json`과 append-only `poggn/version-history.ndjson` ledger를 기록",
      "",
      "### Optional Audits",
      "",
      "- `pgg-token`",
      "  - workflow 자산, state handoff, helper, generated 문서 구조를 점검할 때만 연다",
      "  - 실행된 경우에만 `token/report.md`를 남기고, `required` applicability일 때만 gate에서 강제한다",
      "- `pgg-performance`",
      "  - 성능 민감 변경 또는 선언된 verification contract가 있을 때만 연다",
      "  - 실행된 경우에만 `performance/report.md`를 남기고, `required` applicability일 때만 gate에서 강제한다",
      "",
      ...auditApplicabilityContractSection(input.language),
      "",
      "## 공통 Frontmatter",
      "",
      "```md",
      "---",
      "pgg:",
      "  topic: \"<topic>\"",
      `  stage: "${WORKFLOW_FRONTMATTER_STAGES}"`,
      "  status: \"draft | reviewed | approved | blocked | done\"",
      `  skill: "${WORKFLOW_FRONTMATTER_SKILLS}"`,
      "  score: 0",
      "  updated_at: \"YYYY-MM-DDTHH:mm:ssZ\"",
      "  archive_type: \"feat | fix | docs | refactor | chore | remove\"",
      "  project_scope: \"current-project\"",
      "---",
      "```"
    ]);
  }

  return lines([
    "# Work Flow",
    "",
    "pgg splits delivery into a core workflow plus optional audits that open only when needed.",
    "",
    "## Hard Rules",
    "",
    "- When auto mode is `off`, unresolved requirements stay as options plus free input.",
    "- When `pgg teams` is `on`, stages use expert-based automatic orchestration; when it is `off`, they stay in a single-agent flow.",
    "- Automatically handle stage-local confirmations, records, and generated documents only when the work stays inside the current project.",
    "- Treat only pgg-generated and managed `.codex/sh/*.sh` helpers as trusted workflow scripts that can run without extra approval.",
    "- TTY choice flows use a shared Up/Down plus Enter menu.",
    "- Interactive change commands print changed paths or a no-op/cancel status before exit.",
    "- Confirm scope and exit criteria from `proposal.md`, `plan.md`, and `task.md` before implementation.",
    "- Execute work through `poggn/active/<topic>` documents.",
    "- Resolve `archive_type` and `project_scope` during the proposal stage so later helpers use the same metadata.",
    "- Use only declared current-project verification command contracts for project verification, and do not guess framework commands.",
    "- Move only QA-passed topics to archive.",
    "- Include the required expert review at every stage.",
    "",
    "## Execution Flow",
    "",
    "### Core Workflow",
    "",
    "1. `pgg-add`",
    "   - create a topic",
    "   - create `proposal.md`, `reviews/proposal.review.md`, `state/current.md`, `workflow.reactflow.json`",
    "   - record the user input questions and resolve current-project stage automation metadata plus `archive_type`",
    "2. `pgg-plan`",
    "   - create `plan.md`, `task.md`, `spec/*/*.md`, `reviews/plan.review.md`, `reviews/task.review.md`",
    "3. `pgg-code`",
    "   - implement code",
    "   - create `implementation/index.md`, `implementation/diffs/*.diff`, `reviews/code.review.md`",
    "4. `pgg-refactor`",
    "   - remove legacy code and improve structure",
    "   - create `reviews/refactor.review.md`",
    "5. `pgg-qa`",
    "   - create `qa/report.md`",
    "   - run `.codex/sh/pgg-archive.sh <topic|topic_dir>` when the report passes",
    "   - record `version.json` plus the append-only `poggn/version-history.ndjson` ledger during archive",
    "",
    "### Optional Audits",
    "",
    "- `pgg-token`",
    "  - open only when workflow assets, state handoff, helpers, or generated docs need token-cost review",
    "  - require `token/report.md` only when the audit actually runs and applicability is `required`",
    "- `pgg-performance`",
    "  - open only for performance-sensitive changes or when a declared verification contract supports measurement",
    "  - require `performance/report.md` only when the audit actually runs and applicability is `required`",
    "",
    ...auditApplicabilityContractSection(input.language)
  ]);
}

function stateContractMd(input: TemplateInput): string {
  if (input.language === "ko") {
    return lines([
      "# STATE-CONTRACT",
      "",
      "`state/current.md`는 다음 단계에 전달하는 최소 컨텍스트다.",
      "",
      "## 필수 규칙",
      "",
      "- topic마다 `state/current.md`와 `state/history.ndjson`를 유지한다.",
      "- 다음 단계에는 전체 문서 대신 `state/current.md`를 우선 전달한다.",
      "- teams handoff가 필요하면 먼저 `.codex/sh/pgg-state-pack.sh <topic|topic_dir>`로 최소 컨텍스트를 만든다.",
      "- `pgg teams`가 `off`여도 handoff 형식은 같은 최소 컨텍스트 계약을 유지한다.",
      "- pgg가 생성·관리하는 `.codex/sh/*.sh` helper만 trusted handoff/automation script로 본다.",
      "- `archive_type`, `project_scope`, archive 후의 version 정보는 최소 컨텍스트에 유지한다.",
      "- proposal 단계에서는 사용자 입력 질문 기록 섹션의 위치 또는 ref를 최소 컨텍스트에 유지한다.",
      auditApplicabilityStateRule(input.language),
      "- 변경 파일은 `Changed Files` 섹션에 CRUD와 diff 경로로 기록한다.",
      "- 마지막 전문가 점수와 blocking issue를 유지한다.",
      "- `state/current.md`에는 review 전문을 복사하지 말고 결정, 점수, blocking issue만 요약한다."
    ]);
  }

  return lines([
    "# STATE-CONTRACT",
    "",
    "`state/current.md` is the minimum handoff context for the next stage.",
    "",
    "## Required Rules",
    "",
    "- Keep `state/current.md` and `state/history.ndjson` for every topic.",
    "- Pass `state/current.md` before full documents to the next stage.",
    "- When teams handoff is needed, build the minimum payload with `.codex/sh/pgg-state-pack.sh <topic|topic_dir>` first.",
    "- Keep the same minimal handoff format even when `pgg teams` is `off`.",
    "- Treat only pgg-generated and managed `.codex/sh/*.sh` helpers as trusted handoff and automation scripts.",
    "- Preserve `archive_type`, `project_scope`, and archive version data in the minimum handoff.",
    "- Preserve the user-question record section or reference from the proposal stage in the minimum handoff.",
    auditApplicabilityStateRule(input.language),
    "- Record CRUD and diff paths in the `Changed Files` section.",
    "- Preserve the last expert score and blocking issues.",
    "- Keep full review text out of `state/current.md`; summarize only decisions, score, and blockers."
  ]);
}

function expertRoutingMd(input: TemplateInput): string {
  if (input.language === "ko") {
    return lines([
      "# EXPERT-ROUTING",
      "",
      "## Teams Mode",
      "",
      "- `pgg teams=on`: stage 시작 시 아래 전문가 roster를 자동 orchestration한다.",
      "- `pgg teams=off`: 동일한 문서 계약을 유지하되 단일 에이전트 흐름으로 진행한다.",
      "",
      "## Core Workflow 전문가",
      "",
      "- `pgg-add`: 프로덕트 매니저, UX/UI 전문가, 도메인 전문가",
      "- `pgg-plan`: 소프트웨어 아키텍트, 시니어 백엔드 엔지니어, QA/테스트 엔지니어",
      "- `pgg-code`: 시니어 백엔드 엔지니어, 테크 리드, 코드 리뷰어",
      "- `pgg-refactor`: 소프트웨어 아키텍트, 시니어 백엔드 엔지니어, 코드 리뷰어",
      "- `pgg-qa`: QA/테스트 엔지니어, 코드 리뷰어, SRE / 운영 엔지니어",
      "",
      "## Optional Audit 전문가",
      "",
      "- `pgg-token`: 테크 리드, 시니어 백엔드 엔지니어, 코드 리뷰어",
      "- `pgg-performance`: QA/테스트 엔지니어, 시니어 백엔드 엔지니어, SRE / 운영 엔지니어",
      "",
      "token/performance roster는 모든 topic에 자동 적용되는 기본 stage가 아니라, applicability가 `required`이거나 사용자가 audit를 명시한 경우에만 호출한다.",
    ]);
  }

  return lines([
    "# EXPERT-ROUTING",
    "",
    "## Teams Mode",
    "",
    "- `pgg teams=on`: automatically orchestrate the stage experts below at stage start.",
    "- `pgg teams=off`: keep the same document contract but stay in a single-agent flow.",
    "",
    "## Core Workflow Experts",
    "",
    "- `pgg-add`: product manager, UX/UI expert, domain expert",
    "- `pgg-plan`: software architect, senior backend engineer, QA/test engineer",
    "- `pgg-code`: senior backend engineer, tech lead, code reviewer",
    "- `pgg-refactor`: software architect, senior backend engineer, code reviewer",
    "- `pgg-qa`: QA/test engineer, code reviewer, SRE/operations engineer",
    "",
    "## Optional Audit Experts",
    "",
    "- `pgg-token`: tech lead, senior backend engineer, code reviewer",
    "- `pgg-performance`: QA/test engineer, senior backend engineer, SRE/operations engineer",
    "",
    "The token/performance rosters are optional-audit rosters, not mandatory stages for every topic."
  ]);
}

function implementationMd(input: TemplateInput): string {
  if (input.language === "ko") {
    return lines([
      "# IMPLEMENTATION",
      "",
      "- `pgg-code`와 `pgg-refactor`는 승인된 proposal, plan, task, spec 기준과 필수 구현 기준에 따라 구현한다.",
      "- `pgg-token`과 `pgg-performance`는 optional audit로 실제로 열린 경우에만 각각 `token/report.md`, `performance/report.md`에 결과를 남긴다.",
      "- audit applicability가 `required`인 경우에만 후속 gate와 QA에서 해당 report를 필수로 본다.",
      "- 모든 변경은 `CREATE`, `UPDATE`, `DELETE`로 분류한다.",
      "- `implementation/diffs/*.diff`와 `implementation/index.md`를 유지한다.",
      "- React Flow에는 diff 본문 대신 `diffRef`만 연결한다."
    ]);
  }

  return lines([
    "# IMPLEMENTATION",
    "",
    "- `pgg-code` and `pgg-refactor` implement only approved proposal, plan, task, and spec documents plus the mandatory implementation criteria.",
    "- `pgg-token` and `pgg-performance` write `token/report.md` and `performance/report.md` only when those optional audits actually run.",
    "- Gate and QA treat those reports as required only when audit applicability is `required`.",
    "- Classify every change as `CREATE`, `UPDATE`, or `DELETE`.",
    "- Keep `implementation/diffs/*.diff` and `implementation/index.md` up to date.",
    "- Store only `diffRef` values in React Flow nodes, not full diff bodies."
  ]);
}

function reviewRubricMd(input: TemplateInput): string {
  if (input.language === "ko") {
    return lines([
      "# REVIEW-RUBRIC",
      "",
      "## 공통 기준",
      "",
      "- 범위가 proposal/plan/spec와 일치하는가",
      "- 테스트와 검증 계획이 충분한가",
      "- `pgg-code`와 `pgg-refactor` 결과가 필수 구현 기준을 충족하는가",
      "- 회귀 위험과 미해결 이슈가 기록되었는가",
      "- 다음 단계로 넘길 수 있는 최소 상태가 정리되었는가",
      "",
      "## 필수 형식",
      "",
      "- 각 review 문서는 `Expert Notes` 섹션에서 전문가 이름, 점수, 핵심 판단, blocking issue를 분리한다.",
      "- `proposal`, `plan`, `task`, `code`, `refactor` review는 `reviews/*.review.md` 패턴을 사용한다.",
      "- QA는 `qa/report.md` 안에 테스트 계획, 실행 결과, 전문가 검토, 최종 판정을 함께 기록한다.",
      "- `token/report.md`는 optional audit가 실제로 열렸을 때만 만들고, 측정값, 최적화 액션, 개선 결과를 함께 기록한다.",
      "- `performance/report.md`는 optional audit가 실제로 열렸을 때만 만들고, applicability, baseline, target, actual result 또는 제외 근거를 함께 기록한다.",
      "- QA는 `Audit Applicability` 섹션을 기준으로 `required` audit만 blocking으로 판단한다.",
      "- archive가 포함되는 QA는 `archive_type`, version 기록 여부, ledger 경로를 검증 근거에 남긴다.",
      "- verification contract가 선언되지 않은 프로젝트는 framework 명령을 추론하지 않고 `manual verification required`를 QA 근거에 남긴다.",
      "- `state/current.md`에는 review 원문을 반복하지 않고 score, blocking issue, next action만 남긴다."
    ]);
  }

  return lines([
    "# REVIEW-RUBRIC",
    "",
    "## Common Criteria",
    "",
    "- Does the work match the approved proposal, plan, and spec?",
    "- Are validation and test plans sufficient?",
    "- Do `pgg-code` and `pgg-refactor` outputs satisfy the mandatory implementation criteria?",
    "- Are regression risks and unresolved issues recorded?",
    "- Is the minimum next-stage state ready?",
    "",
    "## Required Format",
    "",
    "- Each review document must separate expert name, score, summary, and blocking issues in an `Expert Notes` section.",
    "- Use the `reviews/*.review.md` pattern for proposal, plan, task, code, and refactor reviews.",
    "- Keep test plan, execution results, expert review, and the final decision together in `qa/report.md`.",
    "- Create `token/report.md` only when the optional audit runs, and keep measurements, optimization actions, and post-change results together.",
    "- Create `performance/report.md` only when the optional audit runs, and keep applicability, baseline, target, actual result, or exclusion evidence together.",
    "- In QA, treat only `required` entries from the `Audit Applicability` section as blocking audit obligations.",
    "- When QA leads to archive, keep the `archive_type`, recorded version, and ledger reference in the evidence.",
    "- When no verification contract is declared, record `manual verification required` in QA evidence instead of guessing framework commands.",
    "- Do not repeat full review text in `state/current.md`; keep only score, blockers, and next action."
  ]);
}

function shellRulesMd(input: TemplateInput): string {
  if (input.language === "ko") {
    return lines([
      "# SHELL-RULES",
      "",
      "토큰 절약을 위해 긴 계산은 shell script가 처리하고 Codex는 짧은 결과만 읽는다.",
      "pgg가 생성·관리하는 `.codex/sh/*.sh` executable helper만 workflow 내부 trusted script로 본다.",
      "이 규칙은 사용자가 따로 만든 임의 shell script에는 확장하지 않는다.",
      "teams handoff에서는 `.codex/sh/pgg-state-pack.sh`를 전체 문서 전달보다 우선한다.",
      "archive version 계산과 append-only NDJSON ledger 기록은 `.codex/sh/pgg-version.sh`가 담당한다.",
      "대상 프로젝트 verification은 freeform shell string이 아니라 current-project 내부 `cwd + argv + timeoutMs (+ env)` contract만 허용한다.",
      "",
      "## 대상 스크립트",
      "",
      "- `.codex/sh/pgg-new-topic.sh`",
      "- `.codex/sh/pgg-state-pack.sh`",
      "- `.codex/sh/pgg-diff.sh`",
      "- `.codex/sh/pgg-diff-index.sh`",
      "- `.codex/sh/pgg-reactflow-build.sh`",
      "- `.codex/sh/pgg-gate.sh`",
      "- `.codex/sh/pgg-version.sh`",
      "- `.codex/sh/pgg-archive.sh`"
    ]);
  }

  return lines([
    "# SHELL-RULES",
    "",
    "Use shell scripts for long mechanical work and keep Codex focused on short results.",
    "Treat only pgg-generated and managed executable `.codex/sh/*.sh` helpers as trusted workflow scripts.",
    "Do not extend this rule to arbitrary user-authored shell scripts.",
    "For teams handoff, prefer `.codex/sh/pgg-state-pack.sh` over copying full documents.",
    "Use `.codex/sh/pgg-version.sh` to calculate archive versions and append the project's NDJSON version ledger.",
    "For project verification, allow only current-project `cwd + argv + timeoutMs (+ env)` contracts instead of freeform shell strings.",
    "",
    "## Scripts",
    "",
    "- `.codex/sh/pgg-new-topic.sh`",
    "- `.codex/sh/pgg-state-pack.sh`",
    "- `.codex/sh/pgg-diff.sh`",
    "- `.codex/sh/pgg-diff-index.sh`",
    "- `.codex/sh/pgg-reactflow-build.sh`",
    "- `.codex/sh/pgg-gate.sh`",
    "- `.codex/sh/pgg-version.sh`",
    "- `.codex/sh/pgg-archive.sh`"
  ]);
}

function skillMd(input: TemplateInput, name: WorkflowSkillName): string {
  const english = {
    "pgg-add": {
      description:
        "Review the requirement and create proposal-stage topic documents.",
      body: [
        "# Skill: pgg-add",
        "",
        "## Purpose",
        "",
        "Create `proposal.md`, a structured user-question record, attributed proposal review notes, state summary, and workflow metadata.",
        "",
        "## Teams Mode",
        "",
        "- when `pgg teams` is `on`, build a minimum handoff with `.codex/sh/pgg-state-pack.sh <topic|topic_dir>` and automatically orchestrate the stage experts below",
        "- when `pgg teams` is `off`, keep the same document contract and stay in a single-agent flow",
        "- treat only pgg-generated and managed `.codex/sh/*.sh` helpers as trusted workflow scripts that can run without extra approval",
        "",
        "## Expert Roster",
        "",
        "- product manager: problem framing, scope, success criteria",
        "- UX/UI expert: user flow and interaction clarity",
        "- domain expert: domain fit and terminology",
        "",
        "## Read",
        "",
        "- user requirement",
        "- `.codex/add/WOKR-FLOW.md`",
        "- `.codex/add/STATE-CONTRACT.md`",
        "- `.codex/add/EXPERT-ROUTING.md`",
        "",
        "## Write",
        "",
        "- `proposal.md`",
        "- a `User Questions` record section inside `proposal.md`",
        "- `reviews/proposal.review.md`",
        "- `state/current.md`",
        "- `workflow.reactflow.json`",
        "- resolve `archive_type` and keep `project_scope` as `current-project` for later stages",
        "",
        "## Handoff",
        "",
        "- automatically handle confirmations, records, and generated documents when the work stays inside the current project",
        "- stop and ask instead of auto-handling when the work would touch paths or systems outside the current project",
        "- keep the user-question record distinct from interpretation, scope, and success-criteria sections",
        "- prefer `state/current.md` and required document refs over full document copies",
        "- make the proposal review explicit about which expert made each judgment"
      ]
    },
    "pgg-plan": {
      description:
        "Turn an approved proposal into plan, task, and supporting spec files.",
      body: [
        "# Skill: pgg-plan",
        "",
        "## Purpose",
        "",
        "Create `plan.md`, `task.md`, related `spec/*/*.md`, `plan/task` review notes.",
        "",
        "## Teams Mode",
        "",
        "- when `pgg teams` is `on`, build a minimum handoff with `.codex/sh/pgg-state-pack.sh <topic|topic_dir>` and automatically orchestrate the stage experts below",
        "- when `pgg teams` is `off`, keep the same document contract and stay in a single-agent flow",
        "- treat only pgg-generated and managed `.codex/sh/*.sh` helpers as trusted workflow scripts that can run without extra approval",
        "",
        "## Expert Roster",
        "",
        "- software architect: spec boundaries and system impact",
        "- senior backend engineer: implementation path and regression risk",
        "- QA/test engineer: validation scope and acceptance checks",
        "",
        "## Rules",
        "",
        "- do not implement",
        "- do not create task without spec",
        "- split tasks by spec boundaries",
        "- automatically handle stage-local confirmations and records only for current-project work",
        "- do not continue automatically when the proposal scope is outside the current project",
        "- write both `reviews/plan.review.md` and `reviews/task.review.md`",
        "- make expert attribution explicit in review notes",
        "- prefer `state/current.md` plus required refs over full document copies",
      ]
    },
    "pgg-code": {
      description:
        "Implement an approved topic and record implementation diffs and reviews.",
      body: [
        "# Skill: pgg-code",
        "",
        "## Purpose",
        "",
        "Implement the approved plan and keep implementation diffs, index, attributed code review, and state updated.",
        "",
        "## Teams Mode",
        "",
        "- when `pgg teams` is `on`, build a minimum handoff with `.codex/sh/pgg-state-pack.sh <topic|topic_dir>` and automatically orchestrate the stage experts below",
        "- when `pgg teams` is `off`, keep the same document contract and stay in a single-agent flow",
        "- treat only pgg-generated and managed `.codex/sh/*.sh` helpers as trusted workflow scripts that can run without extra approval",
        "",
        "## Expert Roster",
        "",
        "- senior backend engineer: primary implementation work",
        "- tech lead: architecture guardrails and integration decisions",
        "- code reviewer: bug and regression review",
        "",
        "## Rules",
        "",
        "- do not implement unapproved topics",
        "- automatically handle current-project implementation records and generated docs without extra user confirmation",
        "- stop instead of auto-running when the change would leave the current project scope",
        "- classify all changes as CREATE, UPDATE, DELETE",
        "- prefer diff records over full file copies",
        "- make expert attribution explicit in `reviews/code.review.md`",
        "- satisfy the mandatory implementation criteria below",
        "- prefer `state/current.md` plus required refs over full document copies",
        ...mandatoryCriteriaSection("en")
      ]
    },
    "pgg-refactor": {
      description:
        "Remove legacy code and improve structure after the implementation stage.",
      body: [
        "# Skill: pgg-refactor",
        "",
        "## Purpose",
        "",
        "Refactor the implemented topic, remove legacy code, improve structure, and keep an attributed refactor review plus state updated.",
        "",
        "## Teams Mode",
        "",
        "- when `pgg teams` is `on`, build a minimum handoff with `.codex/sh/pgg-state-pack.sh <topic|topic_dir>` and automatically orchestrate the stage experts below",
        "- when `pgg teams` is `off`, keep the same document contract and stay in a single-agent flow",
        "- treat only pgg-generated and managed `.codex/sh/*.sh` helpers as trusted workflow scripts that can run without extra approval",
        "",
        "## Expert Roster",
        "",
        "- software architect: structure boundaries and simplification path",
        "- senior backend engineer: concrete refactor implementation",
        "- code reviewer: regression and dead-code review",
        "",
        "## Rules",
        "",
        "- do not widen product scope beyond the approved plan",
        "- automatically handle current-project refactor records and generated docs without extra user confirmation",
        "- stop instead of auto-running when the change would leave the current project scope",
        "- remove legacy paths only when replacement or removal intent is explicit",
        "- make expert attribution explicit in `reviews/refactor.review.md`",
        "- satisfy the mandatory implementation criteria below",
        "- prefer `state/current.md` plus required refs over full document copies",
        ...mandatoryCriteriaSection("en")
      ]
    },
    "pgg-token": {
      description:
        "Run an optional token audit for the pgg workflow and record optimization actions.",
      body: [
        "# Skill: pgg-token",
        "",
        "## Purpose",
        "",
        "Run an optional audit for the current pgg workflow, document the token-cost contributors, and record optimization actions in `token/report.md` only when the audit actually runs.",
        "",
        "## Teams Mode",
        "",
        "- when `pgg teams` is `on`, build a minimum handoff with `.codex/sh/pgg-state-pack.sh <topic|topic_dir>` and automatically orchestrate the stage experts below",
        "- when `pgg teams` is `off`, keep the same document contract and stay in a single-agent flow",
        "- treat only pgg-generated and managed `.codex/sh/*.sh` helpers as trusted workflow scripts that can run without extra approval",
        "",
        "## Expert Roster",
        "",
        "- tech lead: token optimization direction and tradeoffs",
        "- senior backend engineer: workflow and helper implementation detail",
        "- code reviewer: prompt/document duplication and waste review",
        "",
        "## Rules",
        "",
        "- treat this as an optional audit, not a mandatory stage for every topic",
        "- default to `not_required` unless workflow assets, handoff structure, helpers, templates, or generated docs changed in a token-sensitive way",
        "- keep the measurement scope inside the pgg workflow and generated assets",
        "- identify which stage, helper, document, or handoff contributes to token cost",
        "- connect every optimization recommendation to a measured or inferred contributor",
        "- create `token/report.md` only when the audit actually runs",
        "- keep measurements, optimization actions, and post-change results together in `token/report.md`",
        "- prefer `state/current.md` plus required refs over full document copies"
      ]
    },
    "pgg-performance": {
      description:
        "Run an optional performance audit and record evidence only when the topic needs it.",
      body: [
        "# Skill: pgg-performance",
        "",
        "## Purpose",
        "",
        "Run an optional audit for performance-sensitive topics only and keep the applicable results, exclusions, and targets in `performance/report.md` when the audit actually runs.",
        "",
        "## Teams Mode",
        "",
        "- when `pgg teams` is `on`, build a minimum handoff with `.codex/sh/pgg-state-pack.sh <topic|topic_dir>` and automatically orchestrate the stage experts below",
        "- when `pgg teams` is `off`, keep the same document contract and stay in a single-agent flow",
        "- treat only pgg-generated and managed `.codex/sh/*.sh` helpers as trusted workflow scripts that can run without extra approval",
        "",
        "## Expert Roster",
        "",
        "- QA/test engineer: performance measurement scope and evidence",
        "- senior backend engineer: system-path interpretation and bottleneck review",
        "- SRE/operations engineer: runtime limits, recovery, and scalability review",
        "",
        "## Rules",
        "",
        "- treat this as an optional audit, not a mandatory stage for every topic",
        "- default to `not_required` unless the topic has performance-sensitive paths, an explicit user target, or a declared verification contract that supports measurement",
        "- evaluate applicability before measuring each performance item",
        "- record baseline, target, actual result, and method for applicable items",
        "- record explicit exclusion evidence for `not_applicable` items instead of inventing numbers",
        "- create `performance/report.md` only when the audit actually runs",
        "- respect declared current-project verification contracts and keep `manual verification required` when no contract exists",
        "- keep measurements, exclusions, and conclusions together in `performance/report.md`",
        "- prefer `state/current.md` plus required refs over full document copies"
      ]
    },
    "pgg-qa": {
      description:
        "Validate implementation results and record QA outputs before archive.",
      body: [
        "# Skill: pgg-qa",
        "",
        "## Purpose",
        "",
        "Create `qa/report.md` with test planning, results, expert review notes, audit applicability decisions, and archive passing topics.",
        "",
        "## Teams Mode",
        "",
        "- when `pgg teams` is `on`, build a minimum handoff with `.codex/sh/pgg-state-pack.sh <topic|topic_dir>` and automatically orchestrate the stage experts below",
        "- when `pgg teams` is `off`, keep the same document contract and stay in a single-agent flow",
        "- treat only pgg-generated and managed `.codex/sh/*.sh` helpers as trusted workflow scripts that can run without extra approval",
        "",
        "## Expert Roster",
        "",
        "- QA/test engineer: test design and execution evidence",
        "- code reviewer: code-path and regression findings",
        "- SRE/operations engineer: runtime and operational risk review",
        "",
        "## Rules",
        "",
        "- do not archive failing topics",
        "- automatically complete current-project QA records and archive bookkeeping without extra user confirmation",
        "- do not auto-handle work that would touch paths or systems outside the current project",
        "- keep test evidence and attributed review notes in `qa/report.md`",
        "- return only to the minimum earlier stage when failing",
        "- run `.codex/sh/pgg-archive.sh <topic|topic_dir>` when the report passes, and let it record the archive version",
        "- read the `Audit Applicability` section and treat only `required` audits as blocking report obligations",
        "- run project verification only from a declared current-project verification contract; otherwise record `manual verification required`",
        "- prefer `state/current.md` plus required refs over full document copies"
      ]
    }
  } as const;

  const korean = {
    "pgg-add": {
      description:
        "사용자 요구사항을 검토하고 proposal 단계 문서를 생성한다.",
      body: [
        "# Skill: pgg-add",
        "",
        "## Purpose",
        "",
        "`proposal.md`, 사용자 입력 질문 기록, 전문가 attribution이 있는 proposal review, state 요약, workflow 메타데이터를 만든다.",
        "",
        "## Teams Mode",
        "",
        "- `pgg teams`가 `on`이면 `.codex/sh/pgg-state-pack.sh <topic|topic_dir>`로 최소 handoff를 만든 뒤 아래 전문가를 자동 orchestration한다.",
        "- `pgg teams`가 `off`이면 같은 문서 계약을 유지하되 단일 에이전트 흐름으로 진행한다.",
        "- pgg가 생성·관리하는 `.codex/sh/*.sh` helper만 workflow 내부 trusted script로 보고 추가 허락 없이 실행한다.",
        "",
        "## Expert Roster",
        "",
        "- 프로덕트 매니저: 문제 정의, 범위, 성공 기준",
        "- UX/UI 전문가: 사용자 흐름과 상호작용 명확성",
        "- 도메인 전문가: 도메인 적합성과 용어 정합성",
        "",
        "## Read",
        "",
        "- 사용자 요구사항",
        "- `.codex/add/WOKR-FLOW.md`",
        "- `.codex/add/STATE-CONTRACT.md`",
        "- `.codex/add/EXPERT-ROUTING.md`",
        "",
        "## Write",
        "",
        "- `proposal.md`",
        "- `proposal.md` 안의 사용자 입력 질문 기록 섹션",
        "- `reviews/proposal.review.md`",
        "- `state/current.md`",
        "- `workflow.reactflow.json`",
        "- `archive_type`과 `project_scope: current-project` 확정",
        "",
        "## Handoff",
        "",
        "- 현재 프로젝트 내부 확인, 기록, 문서 생성은 추가 사용자 확인 없이 자동 처리한다.",
        "- 현재 프로젝트 밖 경로나 전역 상태를 건드리면 자동 처리하지 않고 중단한다.",
        "- 사용자 질문 기록은 해석/범위/성공 기준과 섞지 않고 별도 섹션으로 유지한다.",
        "- 전체 문서 복사보다 `state/current.md`와 필요한 문서 ref를 우선한다.",
        "- `reviews/proposal.review.md`에는 어떤 전문가가 어떤 판단을 했는지 명시한다."
      ]
    },
    "pgg-plan": {
      description:
        "승인된 proposal을 plan, task, spec 문서로 전개한다.",
      body: [
        "# Skill: pgg-plan",
        "",
        "## Purpose",
        "",
        "`plan.md`, `task.md`, 관련 `spec/*/*.md`, `plan/task` 리뷰를 생성한다.",
        "",
        "## Teams Mode",
        "",
        "- `pgg teams`가 `on`이면 `.codex/sh/pgg-state-pack.sh <topic|topic_dir>`로 최소 handoff를 만든 뒤 아래 전문가를 자동 orchestration한다.",
        "- `pgg teams`가 `off`이면 같은 문서 계약을 유지하되 단일 에이전트 흐름으로 진행한다.",
        "- pgg가 생성·관리하는 `.codex/sh/*.sh` helper만 workflow 내부 trusted script로 보고 추가 허락 없이 실행한다.",
        "",
        "## Expert Roster",
        "",
        "- 소프트웨어 아키텍트: spec 경계와 시스템 영향",
        "- 시니어 백엔드 엔지니어: 구현 경로와 회귀 위험",
        "- QA/테스트 엔지니어: 검증 범위와 acceptance 체크",
        "",
        "## Rules",
        "",
        "- 구현하지 않는다",
        "- spec 없이 task를 만들지 않는다",
        "- task는 spec 경계로 분해한다",
        "- 현재 프로젝트 내부 확인/기록 절차는 자동 처리한다",
        "- proposal이 현재 프로젝트 밖 범위를 가리키면 자동 진행하지 않는다",
        "- `reviews/plan.review.md`와 `reviews/task.review.md`를 모두 남긴다",
        "- review 문서에는 전문가 attribution을 남긴다",
        "- 전체 문서 복사보다 `state/current.md`와 필요한 문서 ref를 우선한다.",
      ]
    },
    "pgg-code": {
      description:
        "승인된 topic을 구현하고 implementation diff와 review를 기록한다.",
      body: [
        "# Skill: pgg-code",
        "",
        "## Purpose",
        "",
        "승인된 plan을 구현하고 implementation diff, index, 전문가 attribution이 있는 code review, state를 갱신한다.",
        "",
        "## Teams Mode",
        "",
        "- `pgg teams`가 `on`이면 `.codex/sh/pgg-state-pack.sh <topic|topic_dir>`로 최소 handoff를 만든 뒤 아래 전문가를 자동 orchestration한다.",
        "- `pgg teams`가 `off`이면 같은 문서 계약을 유지하되 단일 에이전트 흐름으로 진행한다.",
        "- pgg가 생성·관리하는 `.codex/sh/*.sh` helper만 workflow 내부 trusted script로 보고 추가 허락 없이 실행한다.",
        "",
        "## Expert Roster",
        "",
        "- 시니어 백엔드 엔지니어: 주 구현 작업",
        "- 테크 리드: 아키텍처 가드레일과 통합 판단",
        "- 코드 리뷰어: 버그와 회귀 관점 검토",
        "",
        "## Rules",
        "",
        "- 승인되지 않은 topic은 구현하지 않는다",
        "- 현재 프로젝트 내부 implementation 기록과 generated doc 갱신은 자동 처리한다",
        "- 현재 프로젝트 밖을 건드리는 작업은 자동 처리하지 않는다",
        "- 모든 변경은 CREATE, UPDATE, DELETE로 분류한다",
        "- 전체 파일 복사보다 diff 기록을 우선한다",
        "- `reviews/code.review.md`에는 전문가 attribution을 남긴다",
        "- 아래 필수 구현 기준을 충족한다",
        "- 전체 문서 복사보다 `state/current.md`와 필요한 문서 ref를 우선한다.",
        ...mandatoryCriteriaSection("ko")
      ]
    },
    "pgg-refactor": {
      description:
        "레거시 코드를 제거하고 기능 구조를 개선한다.",
      body: [
        "# Skill: pgg-refactor",
        "",
        "## Purpose",
        "",
        "구현된 topic을 리팩터링하고 레거시 코드를 제거하며, `reviews/refactor.review.md`와 state를 갱신한다.",
        "",
        "## Teams Mode",
        "",
        "- `pgg teams`가 `on`이면 `.codex/sh/pgg-state-pack.sh <topic|topic_dir>`로 최소 handoff를 만든 뒤 아래 전문가를 자동 orchestration한다.",
        "- `pgg teams`가 `off`이면 같은 문서 계약을 유지하되 단일 에이전트 흐름으로 진행한다.",
        "- pgg가 생성·관리하는 `.codex/sh/*.sh` helper만 workflow 내부 trusted script로 보고 추가 허락 없이 실행한다.",
        "",
        "## Expert Roster",
        "",
        "- 소프트웨어 아키텍트: 구조 경계와 단순화 판단",
        "- 시니어 백엔드 엔지니어: 실제 리팩터링 구현",
        "- 코드 리뷰어: 회귀와 dead code 검토",
        "",
        "## Rules",
        "",
        "- 승인된 계획 밖으로 제품 범위를 넓히지 않는다",
        "- 현재 프로젝트 내부 refactor 기록과 generated doc 갱신은 자동 처리한다",
        "- 현재 프로젝트 밖을 건드리는 작업은 자동 처리하지 않는다",
        "- 제거 대상은 대체 또는 삭제 의도가 명확할 때만 정리한다",
        "- `reviews/refactor.review.md`에는 전문가 attribution을 남긴다",
        "- 아래 필수 구현 기준을 충족한다",
        "- 전체 문서 복사보다 `state/current.md`와 필요한 문서 ref를 우선한다.",
        ...mandatoryCriteriaSection("ko")
      ]
    },
    "pgg-token": {
      description:
        "필요한 topic에서만 현재 pgg 워크플로우의 token optional audit를 수행한다.",
      body: [
        "# Skill: pgg-token",
        "",
        "## Purpose",
        "",
        "현재 pgg 워크플로우에 대해 필요한 경우에만 optional audit를 수행하고, token 비용 기여 요인과 최적화 액션을 실제 audit가 열렸을 때만 `token/report.md`에 기록한다.",
        "",
        "## Teams Mode",
        "",
        "- `pgg teams`가 `on`이면 `.codex/sh/pgg-state-pack.sh <topic|topic_dir>`로 최소 handoff를 만든 뒤 아래 전문가를 자동 orchestration한다.",
        "- `pgg teams`가 `off`이면 같은 문서 계약을 유지하되 단일 에이전트 흐름으로 진행한다.",
        "- pgg가 생성·관리하는 `.codex/sh/*.sh` helper만 workflow 내부 trusted script로 보고 추가 허락 없이 실행한다.",
        "",
        "## Expert Roster",
        "",
        "- 테크 리드: token 최적화 방향과 trade-off 판단",
        "- 시니어 백엔드 엔지니어: workflow/helper 구현 세부 분석",
        "- 코드 리뷰어: 문서/프롬프트/중복 비용 검토",
        "",
        "## Rules",
        "",
        "- 모든 topic의 기본 stage가 아니라 optional audit로 취급한다",
        "- workflow 자산, handoff 구조, helper, template, generated 문서가 token 비용에 직접 영향을 줄 때만 `required`로 올린다",
        "- 측정 범위는 pgg workflow와 generated asset 내부로 제한한다",
        "- 어떤 stage, helper, 문서, handoff가 token 비용에 기여하는지 식별한다",
        "- 모든 최적화 제안은 측정값 또는 근거 있는 추정과 연결한다",
        "- audit를 실제로 실행한 경우에만 `token/report.md`를 만든다",
        "- 측정값, 최적화 액션, 개선 후 결과를 `token/report.md`에 함께 남긴다",
        "- 전체 문서 복사보다 `state/current.md`와 필요한 문서 ref를 우선한다."
      ]
    },
    "pgg-performance": {
      description:
        "필요한 topic에서만 optional performance audit를 수행하고 결과를 기록한다.",
      body: [
        "# Skill: pgg-performance",
        "",
        "## Purpose",
        "",
        "성능 민감 topic에 대해서만 optional audit를 수행하고, 실제 audit가 열렸을 때만 적용 가능한 성능 항목의 결과와 제외 근거를 `performance/report.md`에 기록한다.",
        "",
        "## Teams Mode",
        "",
        "- `pgg teams`가 `on`이면 `.codex/sh/pgg-state-pack.sh <topic|topic_dir>`로 최소 handoff를 만든 뒤 아래 전문가를 자동 orchestration한다.",
        "- `pgg teams`가 `off`이면 같은 문서 계약을 유지하되 단일 에이전트 흐름으로 진행한다.",
        "- pgg가 생성·관리하는 `.codex/sh/*.sh` helper만 workflow 내부 trusted script로 보고 추가 허락 없이 실행한다.",
        "",
        "## Expert Roster",
        "",
        "- QA/테스트 엔지니어: 성능 측정 범위와 증거",
        "- 시니어 백엔드 엔지니어: 시스템 경로 해석과 병목 검토",
        "- SRE / 운영 엔지니어: 런타임 한계, 복구력, 확장성 검토",
        "",
        "## Rules",
        "",
        "- 모든 topic의 기본 stage가 아니라 optional audit로 취급한다",
        "- 성능 민감 경로, 명시된 성능 목표, 선언된 verification contract가 있을 때만 `required`로 올린다",
        "- 각 성능 항목은 측정 전에 applicability를 먼저 판단한다",
        "- applicable 항목은 baseline, target, actual result, measurement method를 함께 기록한다",
        "- `not_applicable` 항목은 수치를 지어내지 않고 제외 근거를 남긴다",
        "- audit를 실제로 실행한 경우에만 `performance/report.md`를 만든다",
        "- verification contract가 없으면 `manual verification required` 원칙을 유지한다",
        "- 측정값, 제외 근거, 결론을 `performance/report.md`에 함께 남긴다",
        "- 전체 문서 복사보다 `state/current.md`와 필요한 문서 ref를 우선한다."
      ]
    },
    "pgg-qa": {
      description:
        "구현 결과를 검증하고 QA 산출물을 남긴 뒤 archive 여부를 결정한다.",
      body: [
        "# Skill: pgg-qa",
        "",
        "## Purpose",
        "",
        "`qa/report.md`에 테스트 계획, 결과, 전문가 평가, audit applicability 판단, 최종 판정을 함께 기록하고 통과 시 archive한다.",
        "",
        "## Teams Mode",
        "",
        "- `pgg teams`가 `on`이면 `.codex/sh/pgg-state-pack.sh <topic|topic_dir>`로 최소 handoff를 만든 뒤 아래 전문가를 자동 orchestration한다.",
        "- `pgg teams`가 `off`이면 같은 문서 계약을 유지하되 단일 에이전트 흐름으로 진행한다.",
        "- pgg가 생성·관리하는 `.codex/sh/*.sh` helper만 workflow 내부 trusted script로 보고 추가 허락 없이 실행한다.",
        "",
        "## Expert Roster",
        "",
        "- QA/테스트 엔지니어: 테스트 설계와 실행 증거",
        "- 코드 리뷰어: 코드 경로와 회귀 관점 검토",
        "- SRE / 운영 엔지니어: 런타임과 운영 위험 검토",
        "",
        "## Rules",
        "",
        "- 실패한 topic은 archive하지 않는다",
        "- 현재 프로젝트 내부 QA 기록과 archive bookkeeping은 자동 처리한다",
        "- 현재 프로젝트 밖 경로나 시스템을 건드리는 작업은 자동 처리하지 않는다",
        "- 테스트 근거와 전문가 attribution이 있는 review note를 `qa/report.md`에 남긴다",
        "- 실패 시 필요한 최소 이전 단계로만 회귀한다",
        "- pass면 `.codex/sh/pgg-archive.sh <topic|topic_dir>`를 실행하고 archive version을 기록한다",
        "- `Audit Applicability`를 읽고 `required` audit만 blocking report로 판단한다",
        "- 대상 프로젝트 검증은 선언된 current-project verification contract가 있을 때만 실행하고, 없으면 `manual verification required`를 기록한다",
        "- 전체 문서 복사보다 `state/current.md`와 필요한 문서 ref를 우선한다."
      ]
    }
  } as const;

  const entry = input.language === "ko" ? korean[name] : english[name];
  return lines([
    "---",
    `name: "${name}"`,
    `description: "${entry.description}"`,
    "---",
    "",
    ...entry.body
  ]);
}

function newTopicSh(): string {
  return lines([
    "#!/usr/bin/env bash",
    "set -euo pipefail",
    "",
    "if [[ $# -lt 1 || $# -gt 3 ]]; then",
    "  echo \"usage: $0 <topic> [auto_mode:on|off] [archive_type:feat|fix|docs|refactor|chore|remove|pending]\" >&2",
    "  exit 1",
    "fi",
    "",
    "ROOT_DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")/../..\" && pwd)\"",
    "TOPIC=\"$1\"",
    "AUTO_MODE=\"${2:-on}\"",
    "ARCHIVE_TYPE=\"${3:-pending}\"",
    "TOPIC_DIR=\"$ROOT_DIR/poggn/active/$TOPIC\"",
    "TIMESTAMP=\"$(date -u +\"%Y-%m-%dT%H:%M:%SZ\")\"",
    "",
    "mkdir -p \"$TOPIC_DIR/reviews\" \"$TOPIC_DIR/state\"",
    "",
    "cat > \"$TOPIC_DIR/proposal.md\" <<EOF",
    "---",
    "pgg:",
    "  topic: \"$TOPIC\"",
    "  stage: \"proposal\"",
    "  status: \"draft\"",
    "  skill: \"pgg-add\"",
    "  score: 0",
    "  updated_at: \"$TIMESTAMP\"",
    "  auto_mode: \"$AUTO_MODE\"",
    "  archive_type: \"$ARCHIVE_TYPE\"",
    "  project_scope: \"current-project\"",
    "reactflow:",
    "  node_id: \"proposal\"",
    "  node_type: \"doc\"",
    "  label: \"proposal.md\"",
    "state:",
    "  summary: \"사용자 요구사항을 proposal로 정리한다.\"",
    "  next: \"pgg-plan\"",
    "---",
    "",
    "# Proposal",
    "",
    "## 1. 제목",
    "",
    "$TOPIC",
    "",
    "## 2. 변경 분류",
    "",
    "- archive_type: \\`$ARCHIVE_TYPE\\`",
    "- project_scope: \\`current-project\\`",
    "",
    "## 3. 사용자 입력 질문 기록",
    "",
    "- 사용자 입력 질문을 원문 의미 그대로 이 섹션에 기록한다.",
    "EOF",
    "",
    "cat > \"$TOPIC_DIR/reviews/proposal.review.md\" <<EOF",
    "---",
    "pgg:",
    "  topic: \"$TOPIC\"",
    "  stage: \"review\"",
    "  status: \"draft\"",
    "  score: 0",
    "  updated_at: \"$TIMESTAMP\"",
    "---",
    "",
    "# proposal.review",
    "",
    "## Expert Notes",
    "",
    "| Expert | Score | Summary | Blocking |",
    "|---|---:|---|---|",
    "EOF",
    "",
    "cat > \"$TOPIC_DIR/state/current.md\" <<EOF",
    "# Current State",
    "",
    "## Topic",
    "",
    "$TOPIC",
    "",
    "## Current Stage",
    "",
    "proposal",
    "",
    "## Goal",
    "",
    "요구사항을 명확한 proposal로 확정한다.",
    "",
    "## Constraints",
    "",
    "- project scope: \\`current-project\\`",
    "- archive type: \\`$ARCHIVE_TYPE\\`",
    "EOF",
    "",
    "printf '{\"ts\":\"%s\",\"stage\":\"proposal\",\"event\":\"topic-created\"}\\n' \"$TIMESTAMP\" > \"$TOPIC_DIR/state/history.ndjson\"",
    "echo '{\"topic\":\"'$TOPIC'\",\"nodes\":[],\"edges\":[]}' > \"$TOPIC_DIR/workflow.reactflow.json\"",
    "echo \"{\\\"topic\\\":\\\"$TOPIC\\\",\\\"status\\\":\\\"created\\\"}\""
  ]);
}

function gateSh(): string {
  return lines([
    "#!/usr/bin/env bash",
    "set -euo pipefail",
    "",
    "if [[ $# -ne 2 ]]; then",
    "  echo \"usage: $0 <stage> <topic|topic_dir>\" >&2",
    "  exit 1",
    "fi",
    "",
    "ROOT_DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")/../..\" && pwd)\"",
    "STAGE=\"$1\"",
    "TARGET=\"$2\"",
    "",
    "if [[ -d \"$TARGET\" ]]; then",
    "  TOPIC_DIR=\"$TARGET\"",
    "else",
    "  TOPIC_DIR=\"$ROOT_DIR/poggn/active/$TARGET\"",
    "fi",
    "",
    "fail() {",
    "  echo \"{\\\"gate\\\":\\\"fail\\\",\\\"stage\\\":\\\"$STAGE\\\",\\\"reason\\\":\\\"$1\\\"}\"",
    "  exit 1",
    "}",
    "",
    "read_proposal_value() {",
    "  local key=\"$1\"",
    "  local proposal=\"$TOPIC_DIR/proposal.md\"",
    "  [[ -f \"$proposal\" ]] || return 0",
    "  sed -n \"s/^[[:space:]]*${key}: \\\"\\([^\\\"]*\\)\\\"/\\1/p\" \"$proposal\" | head -n 1",
    "}",
    "",
    "extract_state_section() {",
    "  local title=\"$1\"",
    "  local state_file=\"$TOPIC_DIR/state/current.md\"",
    "  [[ -f \"$state_file\" ]] || return 0",
    "  awk -v title=\"$title\" '",
    "    $0 == \"## \" title { found = 1; next }",
    "    /^## / && found { exit }",
    "    found { print }",
    "  ' \"$state_file\" | sed '/^[[:space:]]*$/d'",
    "}",
    "",
    "read_audit_applicability() {",
    "  local audit_name=\"$1\"",
    "  local line",
    "  line=\"$(extract_state_section \"Audit Applicability\" | sed -n \"s/^- \\\`${audit_name}\\\`: \\\`\\([^\\\`]*\\)\\\` | \\(.*\\)$/\\1|\\2/p\" | head -n 1)\"",
    "  if [[ -z \"$line\" ]]; then",
    "    printf 'not_required|state/current.md Audit Applicability not declared\\n'",
    "    return 0",
    "  fi",
    "  printf '%s\\n' \"$line\"",
    "}",
    "",
    "require_audit_report_if_needed() {",
    "  local audit_name=\"$1\"",
    "  local report_path=\"$2\"",
    "  local applicability",
    "  applicability=\"$(read_audit_applicability \"$audit_name\")\"",
    "  local status=\"${applicability%%|*}\"",
    "  local reason=\"${applicability#*|}\"",
    "  if [[ \"$status\" == \"required\" && ! -f \"$report_path\" ]]; then",
    "    fail \"${audit_name} report is required: ${reason}\"",
    "  fi",
    "}",
    "",
    "require_current_project_metadata() {",
    "  local archive_type=\"$(read_proposal_value archive_type)\"",
    "  local project_scope=\"$(read_proposal_value project_scope)\"",
    "  [[ \"$project_scope\" == \"current-project\" ]] || fail \"project_scope must be current-project\"",
    "  case \"$archive_type\" in",
    "    feat|fix|docs|refactor|chore|remove) ;;",
    "    *) fail \"archive_type must be one of feat|fix|docs|refactor|chore|remove\" ;;",
    "  esac",
    "}",
    "",
    "[[ -d \"$TOPIC_DIR\" ]] || fail \"topic not found\"",
    "",
    "case \"$STAGE\" in",
    "  pgg-add)",
    "    [[ -f \"$TOPIC_DIR/proposal.md\" ]] || fail \"proposal.md is missing\"",
    "    ;;",
    "  pgg-plan)",
    "    [[ -f \"$TOPIC_DIR/proposal.md\" ]] || fail \"proposal.md is missing\"",
    "    [[ -f \"$TOPIC_DIR/reviews/proposal.review.md\" ]] || fail \"reviews/proposal.review.md is missing\"",
    "    require_current_project_metadata",
    "    ;;",
    "  pgg-code)",
    "    [[ -f \"$TOPIC_DIR/proposal.md\" ]] || fail \"proposal.md is missing\"",
    "    [[ -f \"$TOPIC_DIR/plan.md\" ]] || fail \"plan.md is missing\"",
    "    [[ -f \"$TOPIC_DIR/task.md\" ]] || fail \"task.md is missing\"",
    "    [[ -f \"$TOPIC_DIR/reviews/plan.review.md\" ]] || fail \"reviews/plan.review.md is missing\"",
    "    [[ -f \"$TOPIC_DIR/reviews/task.review.md\" ]] || fail \"reviews/task.review.md is missing\"",
    "    require_current_project_metadata",
    "    find \"$TOPIC_DIR/spec\" -type f -name '*.md' | grep -q . || fail \"spec files are missing\"",
    "    ;;",
    "  pgg-refactor)",
    "    [[ -f \"$TOPIC_DIR/implementation/index.md\" ]] || fail \"implementation/index.md is missing\"",
    "    [[ -f \"$TOPIC_DIR/reviews/code.review.md\" ]] || fail \"reviews/code.review.md is missing\"",
    "    require_current_project_metadata",
    "    ;;",
    "  pgg-token)",
    "    [[ -f \"$TOPIC_DIR/implementation/index.md\" ]] || fail \"implementation/index.md is missing\"",
    "    [[ -f \"$TOPIC_DIR/reviews/code.review.md\" ]] || fail \"reviews/code.review.md is missing\"",
    "    [[ -f \"$TOPIC_DIR/reviews/refactor.review.md\" ]] || fail \"reviews/refactor.review.md is missing\"",
    "    require_current_project_metadata",
    "    ;;",
    "  pgg-performance)",
    "    [[ -f \"$TOPIC_DIR/implementation/index.md\" ]] || fail \"implementation/index.md is missing\"",
    "    [[ -f \"$TOPIC_DIR/reviews/code.review.md\" ]] || fail \"reviews/code.review.md is missing\"",
    "    [[ -f \"$TOPIC_DIR/reviews/refactor.review.md\" ]] || fail \"reviews/refactor.review.md is missing\"",
    "    require_audit_report_if_needed \"pgg-token\" \"$TOPIC_DIR/token/report.md\"",
    "    require_current_project_metadata",
    "    ;;",
    "  pgg-qa)",
    "    [[ -f \"$TOPIC_DIR/implementation/index.md\" ]] || fail \"implementation/index.md is missing\"",
    "    [[ -f \"$TOPIC_DIR/reviews/code.review.md\" ]] || fail \"reviews/code.review.md is missing\"",
    "    [[ -f \"$TOPIC_DIR/reviews/refactor.review.md\" ]] || fail \"reviews/refactor.review.md is missing\"",
    "    require_audit_report_if_needed \"pgg-token\" \"$TOPIC_DIR/token/report.md\"",
    "    require_audit_report_if_needed \"pgg-performance\" \"$TOPIC_DIR/performance/report.md\"",
    "    require_current_project_metadata",
    "    ;;",
    "  *)",
    "    fail \"unknown stage\"",
    "    ;;",
    "esac",
    "",
    "echo \"{\\\"gate\\\":\\\"pass\\\",\\\"stage\\\":\\\"$STAGE\\\"}\""
  ]);
}

function diffSh(): string {
  return lines([
    "#!/usr/bin/env bash",
    "set -euo pipefail",
    "",
    "echo '{\"error\":\"git-based diff generation is not bundled in generated templates by default\"}' >&2",
    "exit 1"
  ]);
}

function diffIndexSh(): string {
  return lines([
    "#!/usr/bin/env bash",
    "set -euo pipefail",
    "",
    "if [[ $# -ne 1 ]]; then",
    "  echo \"usage: $0 <topic|topic_dir>\" >&2",
    "  exit 1",
    "fi",
    "",
    "ROOT_DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")/../..\" && pwd)\"",
    "TARGET=\"$1\"",
    "if [[ -d \"$TARGET\" ]]; then",
    "  TOPIC_DIR=\"$TARGET\"",
    "else",
    "  TOPIC_DIR=\"$ROOT_DIR/poggn/active/$TARGET\"",
    "fi",
    "TOPIC=\"$(basename \"$TOPIC_DIR\")\"",
    "OUT=\"$TOPIC_DIR/implementation/index.md\"",
    "TIMESTAMP=\"$(date -u +\"%Y-%m-%dT%H:%M:%SZ\")\"",
    "",
    "mkdir -p \"$TOPIC_DIR/implementation\"",
    "cat > \"$OUT\" <<EOF",
    "---",
    "pgg:",
    "  topic: \"$TOPIC\"",
    "  stage: \"implementation\"",
    "  status: \"reviewed\"",
    "  skill: \"pgg-code\"",
    "  score: 0",
    "  updated_at: \"$TIMESTAMP\"",
    "---",
    "",
    "# Implementation Index",
    "",
    "| ID | CRUD | path | diffRef | taskRef | note |",
    "|---|---|---|---|---|---|",
    "EOF",
    "",
    "count=0",
    "for diff_file in \"$TOPIC_DIR\"/implementation/diffs/*.diff; do",
    "  [[ -f \"$diff_file\" ]] || continue",
    "  filename=\"$(basename \"$diff_file\")\"",
    "  id=\"${filename%%_*}\"",
    "  rest=\"${filename#*_}\"",
    "  crud=\"${rest%%_*}\"",
    "  path_value=\"$(awk '/^\\+\\+\\+ b\\// {sub(/^\\+\\+\\+ b\\//, \"\", $0); print; exit}' \"$diff_file\")\"",
    "  printf '| %s | %s | `%s` | `implementation/diffs/%s` | `TBD` | |\\n' \"$id\" \"$crud\" \"$path_value\" \"$filename\" >> \"$OUT\"",
    "  count=$((count + 1))",
    "done",
    "",
    "echo \"{\\\"index\\\":\\\"implementation/index.md\\\",\\\"items\\\":$count}\""
  ]);
}

function reactflowBuildSh(): string {
  return lines([
    "#!/usr/bin/env bash",
    "set -euo pipefail",
    "",
    "if [[ $# -ne 1 ]]; then",
    "  echo \"usage: $0 <topic|topic_dir>\" >&2",
    "  exit 1",
    "fi",
    "",
    "ROOT_DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")/../..\" && pwd)\"",
    "TARGET=\"$1\"",
    "if [[ -d \"$TARGET\" ]]; then",
    "  TOPIC_DIR=\"$TARGET\"",
    "else",
    "  TOPIC_DIR=\"$ROOT_DIR/poggn/active/$TARGET\"",
    "fi",
    "TOPIC=\"$(basename \"$TOPIC_DIR\")\"",
    "",
    "cat > \"$TOPIC_DIR/workflow.reactflow.json\" <<EOF",
    "{",
    "  \"topic\": \"$TOPIC\",",
    "  \"nodes\": [],",
    "  \"edges\": []",
    "}",
    "EOF",
    "",
    "echo \"{\\\"workflow\\\":\\\"workflow.reactflow.json\\\",\\\"nodes\\\":0,\\\"edges\\\":0}\""
  ]);
}

function statePackSh(): string {
  return lines([
    "#!/usr/bin/env bash",
    "set -euo pipefail",
    "",
    "if [[ $# -ne 1 ]]; then",
    "  echo \"usage: $0 <topic|topic_dir>\" >&2",
    "  exit 1",
    "fi",
    "",
    "ROOT_DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")/../..\" && pwd)\"",
    "TARGET=\"$1\"",
    "if [[ -d \"$TARGET\" ]]; then",
    "  TOPIC_DIR=\"$TARGET\"",
    "else",
    "  TOPIC_DIR=\"$ROOT_DIR/poggn/active/$TARGET\"",
    "  if [[ ! -d \"$TOPIC_DIR\" ]]; then",
    "    TOPIC_DIR=\"$ROOT_DIR/poggn/archive/$TARGET\"",
    "  fi",
    "fi",
    "",
    "[[ -d \"$TOPIC_DIR\" ]] || { echo '{\"error\":\"topic not found\"}' >&2; exit 1; }",
    "STATE_FILE=\"$TOPIC_DIR/state/current.md\"",
    "[[ -f \"$STATE_FILE\" ]] || { echo '{\"error\":\"state/current.md not found\"}' >&2; exit 1; }",
    "",
    "to_rel() {",
    "  local value=\"$1\"",
    "  if [[ \"$value\" == \"$ROOT_DIR/\"* ]]; then",
    "    printf '%s\\n' \"${value#$ROOT_DIR/}\"",
    "  else",
    "    printf '%s\\n' \"$value\"",
    "  fi",
    "}",
    "",
    "extract_section() {",
    "  local title=\"$1\"",
    "  awk -v title=\"$title\" '",
    "    $0 == \"## \" title { found = 1; next }",
    "    /^## / && found { exit }",
    "    found { print }",
    "  ' \"$STATE_FILE\" | sed '/^[[:space:]]*$/d'",
    "}",
    "",
    "read_json_field() {",
    "  local key=\"$1\"",
    "  local manifest=\"$ROOT_DIR/.pgg/project.json\"",
    "  if [[ ! -f \"$manifest\" ]]; then",
    "    return 0",
    "  fi",
    "  sed -n \"s/.*\\\"${key}\\\": \\\"\\([^\\\"]*\\)\\\".*/\\1/p\" \"$manifest\" | head -n 1",
    "}",
    "",
    "read_proposal_field() {",
    "  local key=\"$1\"",
    "  local proposal=\"$TOPIC_DIR/proposal.md\"",
    "  [[ -f \"$proposal\" ]] || return 0",
    "  sed -n \"s/^[[:space:]]*${key}: \\\"\\([^\\\"]*\\)\\\"/\\1/p\" \"$proposal\" | head -n 1",
    "}",
    "",
    "read_version_field() {",
    "  local key=\"$1\"",
    "  local version_file=\"$TOPIC_DIR/version.json\"",
    "  [[ -f \"$version_file\" ]] || return 0",
    "  sed -n \"s/.*\\\"${key}\\\": \\\"\\([^\\\"]*\\)\\\".*/\\1/p\" \"$version_file\" | head -n 1",
    "}",
    "",
    "TOPIC=\"$(extract_section \"Topic\" | head -n 1)\"",
    "STAGE=\"$(extract_section \"Current Stage\" | head -n 1)\"",
    "GOAL=\"$(extract_section \"Goal\" | tr '\\n' ' ' | sed 's/[[:space:]]\\+/ /g; s/^ //; s/ $//')\"",
    "NEXT_ACTION=\"$(extract_section \"Next Action\" | tr '\\n' ' ' | sed 's/[[:space:]]\\+/ /g; s/^ //; s/ $//')\"",
    "AUTO_MODE=\"$(read_json_field autoMode)\"",
    "TEAMS_MODE=\"$(read_json_field teamsMode)\"",
    "ARCHIVE_TYPE=\"$(read_proposal_field archive_type)\"",
    "PROJECT_SCOPE=\"$(read_proposal_field project_scope)\"",
    "ARCHIVE_VERSION=\"$(read_version_field version)\"",
    "",
    "printf 'topic: %s\\n' \"${TOPIC:-$(basename \"$TOPIC_DIR\")}\"",
    "printf 'topic_dir: %s\\n' \"$(to_rel \"$TOPIC_DIR\")\"",
    "printf 'current_stage: %s\\n' \"${STAGE:-unknown}\"",
    "printf 'auto_mode: %s\\n' \"${AUTO_MODE:-on}\"",
    "printf 'teams_mode: %s\\n' \"${TEAMS_MODE:-off}\"",
    "printf 'project_scope: %s\\n' \"${PROJECT_SCOPE:-}\"",
    "printf 'archive_type: %s\\n' \"${ARCHIVE_TYPE:-}\"",
    "printf 'archive_version: %s\\n' \"${ARCHIVE_VERSION:-}\"",
    "printf 'goal: %s\\n' \"${GOAL:-}\"",
    "printf 'next_action: %s\\n' \"${NEXT_ACTION:-}\"",
    "printf 'refs:\\n'",
    "printf -- '- %s\\n' \"$(to_rel \"$STATE_FILE\")\"",
    "for ref in \"$TOPIC_DIR/proposal.md\" \"$TOPIC_DIR/plan.md\" \"$TOPIC_DIR/task.md\" \"$TOPIC_DIR/implementation/index.md\" \"$TOPIC_DIR/reviews/code.review.md\" \"$TOPIC_DIR/reviews/refactor.review.md\" \"$TOPIC_DIR/token/report.md\" \"$TOPIC_DIR/performance/report.md\" \"$TOPIC_DIR/qa/report.md\"; do",
    "  [[ -f \"$ref\" ]] || continue",
    "  printf -- '- %s\\n' \"$(to_rel \"$ref\")\"",
    "done",
    "while IFS= read -r spec_path; do",
    "  [[ -n \"$spec_path\" ]] || continue",
    "  printf -- '- %s\\n' \"$(to_rel \"$spec_path\")\"",
    "done < <(find \"$TOPIC_DIR/spec\" -type f -name '*.md' 2>/dev/null | sort)",
    "",
    "ACTIVE_SPECS=\"$(extract_section \"Active Specs\")\"",
    "ACTIVE_TASKS=\"$(extract_section \"Active Tasks\")\"",
    "AUDIT_APPLICABILITY=\"$(extract_section \"Audit Applicability\")\"",
    "if [[ -n \"$ACTIVE_SPECS\" ]]; then",
    "  printf 'active_specs:\\n%s\\n' \"$ACTIVE_SPECS\"",
    "fi",
    "if [[ -n \"$ACTIVE_TASKS\" ]]; then",
    "  printf 'active_tasks:\\n%s\\n' \"$ACTIVE_TASKS\"",
    "fi",
    "if [[ -n \"$AUDIT_APPLICABILITY\" ]]; then",
    "  printf 'audit_applicability:\\n%s\\n' \"$AUDIT_APPLICABILITY\"",
    "fi"
  ]);
}

function versionSh(): string {
  return lines([
    "#!/usr/bin/env bash",
    "set -euo pipefail",
    "",
    "if [[ $# -ne 1 ]]; then",
    "  echo \"usage: $0 <archived-topic|topic_dir>\" >&2",
    "  exit 1",
    "fi",
    "",
    "ROOT_DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")/../..\" && pwd)\"",
    "TARGET=\"$1\"",
    "",
    "fail() {",
    "  echo \"{\\\"error\\\":\\\"$1\\\"}\" >&2",
    "  exit 1",
    "}",
    "",
    "if [[ -d \"$TARGET\" ]]; then",
    "  TOPIC_DIR=\"$(cd \"$TARGET\" && pwd)\"",
    "else",
    "  TOPIC_DIR=\"$ROOT_DIR/poggn/archive/$TARGET\"",
    "fi",
    "",
    "[[ -d \"$TOPIC_DIR\" ]] || fail \"archived topic not found\"",
    "[[ \"$TOPIC_DIR\" == \"$ROOT_DIR/poggn/archive/\"* ]] || fail \"topic must be archived before versioning\"",
    "",
    "PROPOSAL=\"$TOPIC_DIR/proposal.md\"",
    "STATE_HISTORY=\"$TOPIC_DIR/state/history.ndjson\"",
    "LEDGER=\"$ROOT_DIR/poggn/version-history.ndjson\"",
    "VERSION_FILE=\"$TOPIC_DIR/version.json\"",
    "",
    "[[ -f \"$PROPOSAL\" ]] || fail \"proposal.md not found\"",
    "[[ -f \"$STATE_HISTORY\" ]] || fail \"state/history.ndjson not found\"",
    "",
    "read_proposal_field() {",
    "  local key=\"$1\"",
    "  sed -n \"s/^[[:space:]]*${key}: \\\"\\([^\\\"]*\\)\\\"/\\1/p\" \"$PROPOSAL\" | head -n 1",
    "}",
    "",
    "ARCHIVE_TYPE=\"$(read_proposal_field archive_type)\"",
    "PROJECT_SCOPE=\"$(read_proposal_field project_scope)\"",
    "TOPIC=\"$(basename \"$TOPIC_DIR\")\"",
    "",
    "[[ \"$PROJECT_SCOPE\" == \"current-project\" ]] || fail \"project_scope must be current-project\"",
    "case \"$ARCHIVE_TYPE\" in",
    "  feat|fix|docs|refactor|chore|remove) ;;",
    "  *) fail \"archive_type must be one of feat|fix|docs|refactor|chore|remove\" ;;",
    "esac",
    "",
    "mkdir -p \"$ROOT_DIR/poggn\"",
    "touch \"$LEDGER\"",
    "",
    "PREVIOUS_VERSION=\"$(node -e \"const fs=require('fs'); const file=process.argv[1]; const raw=fs.readFileSync(file,'utf8'); const lines=raw.split(/\\n+/).map((line)=>line.trim()).filter(Boolean).reverse(); let version='0.0.0'; for (const line of lines) { try { const data=JSON.parse(line); version=data.version || '0.0.0'; break; } catch {} } process.stdout.write(version);\" \"$LEDGER\")\"",
    "NEXT_VERSION=\"$(node -e \"const current=(process.argv[1]||'0.0.0').split('.').map(Number); const type=process.argv[2]; let [major,minor,patch]=[current[0]||0,current[1]||0,current[2]||0]; if (type==='remove') { major += 1; minor = 0; patch = 0; } else if (type==='feat') { minor += 1; patch = 0; } else { patch += 1; } process.stdout.write([major,minor,patch].join('.'));\" \"$PREVIOUS_VERSION\" \"$ARCHIVE_TYPE\")\"",
    "TIMESTAMP=\"$(date -u +\"%Y-%m-%dT%H:%M:%SZ\")\"",
    "",
    "cat > \"$VERSION_FILE\" <<EOF",
    "{",
    "  \"topic\": \"$TOPIC\",",
    "  \"changeType\": \"$ARCHIVE_TYPE\",",
    "  \"version\": \"$NEXT_VERSION\",",
    "  \"previousVersion\": \"$PREVIOUS_VERSION\",",
    "  \"projectScope\": \"$PROJECT_SCOPE\",",
    "  \"archivedAt\": \"$TIMESTAMP\",",
    "  \"history\": \"poggn/version-history.ndjson\"",
    "}",
    "EOF",
    "",
    "printf '{\"topic\":\"%s\",\"changeType\":\"%s\",\"version\":\"%s\",\"previousVersion\":\"%s\",\"projectScope\":\"%s\",\"archivedAt\":\"%s\",\"history\":\"poggn/version-history.ndjson\"}\\n' \"$TOPIC\" \"$ARCHIVE_TYPE\" \"$NEXT_VERSION\" \"$PREVIOUS_VERSION\" \"$PROJECT_SCOPE\" \"$TIMESTAMP\" >> \"$LEDGER\"",
    "printf '{\"ts\":\"%s\",\"stage\":\"archive\",\"event\":\"version-recorded\",\"version\":\"%s\",\"changeType\":\"%s\"}\\n' \"$TIMESTAMP\" \"$NEXT_VERSION\" \"$ARCHIVE_TYPE\" >> \"$STATE_HISTORY\"",
    "echo \"{\\\"topic\\\":\\\"$TOPIC\\\",\\\"changeType\\\":\\\"$ARCHIVE_TYPE\\\",\\\"version\\\":\\\"$NEXT_VERSION\\\",\\\"previousVersion\\\":\\\"$PREVIOUS_VERSION\\\",\\\"history\\\":\\\"poggn/version-history.ndjson\\\",\\\"versionFile\\\":\\\"poggn/archive/$TOPIC/version.json\\\"}\""
  ]);
}

function archiveSh(): string {
  return lines([
    "#!/usr/bin/env bash",
    "set -euo pipefail",
    "",
    "if [[ $# -ne 1 ]]; then",
    "  echo \"usage: $0 <topic|topic_dir>\" >&2",
    "  exit 1",
    "fi",
    "",
    "ROOT_DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")/../..\" && pwd)\"",
    "TARGET=\"$1\"",
    "",
    "fail() {",
    "  echo \"{\\\"error\\\":\\\"$1\\\"}\" >&2",
    "  exit 1",
    "}",
    "",
    "read_proposal_field() {",
    "  local key=\"$1\"",
    "  local proposal=\"$SRC/proposal.md\"",
    "  [[ -f \"$proposal\" ]] || return 0",
    "  sed -n \"s/^[[:space:]]*${key}: \\\"\\([^\\\"]*\\)\\\"/\\1/p\" \"$proposal\" | head -n 1",
    "}",
    "",
    "extract_section() {",
    "  local file_path=\"$1\"",
    "  local title=\"$2\"",
    "  awk -v title=\"$title\" '",
    "    $0 == \"## \" title { found = 1; next }",
    "    /^## / && found { exit }",
    "    found { print }",
    "  ' \"$file_path\" | sed '/^[[:space:]]*$/d'",
    "}",
    "",
    "if [[ -d \"$TARGET\" ]]; then",
    "  SRC=\"$(cd \"$TARGET\" && pwd)\"",
    "else",
    "  SRC=\"$ROOT_DIR/poggn/active/$TARGET\"",
    "fi",
    "",
    "[[ -d \"$SRC\" ]] || fail \"topic not found\"",
    "[[ \"$SRC\" == \"$ROOT_DIR/poggn/active/\"* ]] || fail \"topic must be in active\"",
    "",
    "TOPIC=\"$(basename \"$SRC\")\"",
    "DST=\"$ROOT_DIR/poggn/archive/$TOPIC\"",
    "STATE_FILE=\"$SRC/state/current.md\"",
    "PROPOSAL=\"$SRC/proposal.md\"",
    "QA_REPORT=\"$SRC/qa/report.md\"",
    "",
    "[[ -f \"$PROPOSAL\" ]] || fail \"proposal.md not found\"",
    "[[ -f \"$STATE_FILE\" ]] || fail \"state/current.md not found\"",
    "[[ -f \"$QA_REPORT\" ]] || fail \"qa/report.md not found\"",
    "",
    "ARCHIVE_TYPE=\"$(read_proposal_field archive_type)\"",
    "PROJECT_SCOPE=\"$(read_proposal_field project_scope)\"",
    "CURRENT_STAGE=\"$(extract_section \"$STATE_FILE\" \"Current Stage\" | head -n 1 | tr '[:upper:]' '[:lower:]')\"",
    "DECISION_TEXT=\"$(extract_section \"$QA_REPORT\" \"Decision\" | tr '\\n' ' ' | tr '[:upper:]' '[:lower:]')\"",
    "",
    "[[ \"$PROJECT_SCOPE\" == \"current-project\" ]] || fail \"project_scope must be current-project\"",
    "case \"$ARCHIVE_TYPE\" in",
    "  feat|fix|docs|refactor|chore|remove) ;;",
    "  *) fail \"archive_type must be one of feat|fix|docs|refactor|chore|remove\" ;;",
    "esac",
    "grep -q 'stage: \"qa\"' \"$QA_REPORT\" || fail \"qa/report.md stage is not qa\"",
    "grep -q 'status: \"done\"' \"$QA_REPORT\" || fail \"qa/report.md status is not done\"",
    "[[ \"$CURRENT_STAGE\" == \"qa\" ]] || fail \"state is not in qa stage\"",
    "[[ \"$DECISION_TEXT\" == *\"pass\"* ]] || fail \"qa decision is not pass\"",
    "",
    "mkdir -p \"$ROOT_DIR/poggn/archive\"",
    "mv \"$SRC\" \"$DST\"",
    "VERSION_JSON=\"$(\"$ROOT_DIR/.codex/sh/pgg-version.sh\" \"$DST\")\"",
    "TIMESTAMP=\"$(date -u +\"%Y-%m-%dT%H:%M:%SZ\")\"",
    "printf '{\"ts\":\"%s\",\"stage\":\"archive\",\"event\":\"archived\"}\\n' \"$TIMESTAMP\" >> \"$DST/state/history.ndjson\"",
    "RESULT_JSON=\"{\\\"status\\\":\\\"archived\\\",${VERSION_JSON#\\{}\"",
    "echo \"$RESULT_JSON\""
  ]);
}

function dashboardKeep(): string {
  return "";
}

export function buildGeneratedFiles(input: TemplateInput): GeneratedFileTemplate[] {
  return [
    { path: "AGENTS.md", content: agentsMd(input) },
    { path: ".codex/add/WOKR-FLOW.md", content: workFlowMd(input) },
    { path: ".codex/add/STATE-CONTRACT.md", content: stateContractMd(input) },
    { path: ".codex/add/EXPERT-ROUTING.md", content: expertRoutingMd(input) },
    { path: ".codex/add/IMPLEMENTATION.md", content: implementationMd(input) },
    { path: ".codex/add/REVIEW-RUBRIC.md", content: reviewRubricMd(input) },
    { path: ".codex/add/SHELL-RULES.md", content: shellRulesMd(input) },
    { path: ".codex/skills/pgg-add/SKILL.md", content: skillMd(input, "pgg-add") },
    { path: ".codex/skills/pgg-plan/SKILL.md", content: skillMd(input, "pgg-plan") },
    { path: ".codex/skills/pgg-code/SKILL.md", content: skillMd(input, "pgg-code") },
    { path: ".codex/skills/pgg-refactor/SKILL.md", content: skillMd(input, "pgg-refactor") },
    { path: ".codex/skills/pgg-token/SKILL.md", content: skillMd(input, "pgg-token") },
    { path: ".codex/skills/pgg-performance/SKILL.md", content: skillMd(input, "pgg-performance") },
    { path: ".codex/skills/pgg-qa/SKILL.md", content: skillMd(input, "pgg-qa") },
    { path: ".codex/sh/pgg-new-topic.sh", content: newTopicSh(), executable: true },
    { path: ".codex/sh/pgg-gate.sh", content: gateSh(), executable: true },
    { path: ".codex/sh/pgg-diff.sh", content: diffSh(), executable: true },
    { path: ".codex/sh/pgg-diff-index.sh", content: diffIndexSh(), executable: true },
    { path: ".codex/sh/pgg-reactflow-build.sh", content: reactflowBuildSh(), executable: true },
    { path: ".codex/sh/pgg-state-pack.sh", content: statePackSh(), executable: true },
    { path: ".codex/sh/pgg-version.sh", content: versionSh(), executable: true },
    { path: ".codex/sh/pgg-archive.sh", content: archiveSh(), executable: true },
    { path: "poggn/active/.gitkeep", content: dashboardKeep() },
    { path: "poggn/archive/.gitkeep", content: dashboardKeep() },
    { path: "poggn/version-history.ndjson", content: dashboardKeep(), preserveExistingContent: true }
  ];
}
